import { tools_version } from "./tools";
import {
  create_filter_preset,
  delete_filter_preset,
  list_filter_presets,
  update_filter_preset,
} from "./tools_handlers/filters";
import {
  create_findings_from_requests,
  delete_findings,
  get_finding_by_id,
  list_findings,
  update_finding,
} from "./tools_handlers/findings";
import {
  clear_replay_entry_draft,
  create_replay_collection,
  create_websocket_replay_session,
  get_replay_session,
  graphql_collection_requests,
  graphql_list_collections,
  list_replay_collections,
  list_replay_connections,
  list_replay_sessions,
  move_replay_session,
  rename_replay_collection,
  rename_replay_session,
  send_to_replay,
  send_websocket_replay_draft,
  send_websocket_replay_message,
  start_replay_task,
  stop_websocket_replay_tasks,
  update_http_replay_draft,
  update_websocket_replay_draft,
} from "./tools_handlers/replay";
import {
  list_by_httpql,
  sendRequest,
  view_request_by_id,
  view_response_by_id,
} from "./tools_handlers/requests";
import {
  create_scope,
  delete_scope,
  list_scopes,
  update_scope,
} from "./tools_handlers/scopes";
import {
  create_tamper_rule,
  create_tamper_rule_collection,
  list_tamper_rule_collections,
  list_tamper_rules,
  read_tamper_rule,
  update_tamper_rule,
} from "./tools_handlers/tampers";
import {
  get_websocket_message,
  get_websocket_message_count,
  get_websocket_stream,
  list_websocket_messages,
  list_websocket_streams,
} from "./tools_handlers/websockets";
import {
  create_workflow,
  delete_workflow,
  generate_workflow_template,
  get_workflow,
  get_workflow_definition_guide,
  globalize_workflow,
  list_workflow_node_definitions,
  list_workflows,
  localize_workflow,
  rename_workflow,
  run_active_workflow,
  run_convert_workflow,
  test_active_workflow,
  test_convert_workflow,
  test_passive_workflow,
  toggle_workflow,
  update_workflow,
} from "./tools_handlers/workflows";

// Handler for getting tools version
const get_tools_version = () => {
  return {
    success: true,
    version: tools_version,
    timestamp: new Date().toISOString(),
    summary: `Backend tools version: ${tools_version}`,
  };
};

export const handlers = {
  list_by_httpql,
  view_request_by_id,
  view_response_by_id,
  sendRequest,
  send_to_replay,
  list_replay_collections,
  rename_replay_collection,
  rename_replay_session,
  graphql_collection_requests,
  graphql_list_collections,
  list_replay_connections,
  list_replay_sessions,
  get_replay_session,
  move_replay_session,
  start_replay_task,
  create_replay_collection,
  create_websocket_replay_session,
  update_http_replay_draft,
  update_websocket_replay_draft,
  clear_replay_entry_draft,
  send_websocket_replay_message,
  send_websocket_replay_draft,
  stop_websocket_replay_tasks,
  create_tamper_rule_collection,
  create_tamper_rule,
  update_tamper_rule,
  list_tamper_rule_collections,
  list_tamper_rules,
  read_tamper_rule,
  list_findings,
  get_finding_by_id,
  update_finding,
  delete_findings,
  create_findings_from_requests,
  list_websocket_streams,
  get_websocket_stream,
  list_websocket_messages,
  get_websocket_message_count,
  get_websocket_message,
  list_workflows,
  get_workflow,
  list_workflow_node_definitions,
  get_workflow_definition_guide,
  generate_workflow_template,
  create_workflow,
  update_workflow,
  rename_workflow,
  delete_workflow,
  globalize_workflow,
  localize_workflow,
  toggle_workflow,
  run_active_workflow,
  run_convert_workflow,
  test_active_workflow,
  test_passive_workflow,
  test_convert_workflow,
  list_filter_presets,
  create_filter_preset,
  update_filter_preset,
  delete_filter_preset,
  list_scopes,
  create_scope,
  update_scope,
  delete_scope,
  get_tools_version,
};
